spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/sagadb?currentSchema=order_schema
    username: saga
    password: saga123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate          # Flyway owns schema creation, JPA just validates
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: order_schema

  flyway:
    enabled: true
    schemas: order_schema
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false   # Don't embed Java class names in message headers
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics